### ISSUE TITLE
Multiple Dimensions in LOD

### ISSUE THREAD

**Issue by Krishnakanthdev** [tableau/extension-quick-what-if#4]
Hi
I am unable to pass mutiple dimensions in the LOD function.
 **eg: SUM([Net Sales])*(1+(MIN(

{FIXED [Class],[Sub Class]: MIN(FLOAT(REGEXP_EXTRACT([What if extension ], [Class],[Sub Class}+"\|(-?\d*\.?\d*)")))}

)/100))**

here I would like to do a what-if analysis at the **SUBCLASS** level.

**Comment by KeshiaRose** [comment]
Hi @Krishnakanthdev, instead of using multiple dimensions you will need to select just one for your setup and calculation. So in this case you should just use [Sub Class]. If a Sub Class can belong to multiple Classes then create a combined field with a calculation like: `[Class] + "-" + [Sub Class]` and use that as your dimension instead. Let me know if you get it working!
-Keshia
